#!/bin/bash

sudo -i

timedatectl set-timezone America/Sao_Paulo

apt update -y && apt upgrade -y && apt autoremove -y 

apt-get install \
jq \
wget \
curl \
udisks2 \
libglib2.0-bin \
network-manager \
iputils-ping \
firewalld \
vim \
openssh-server \
dbus -y

fallocate -l 3G /swapfile
chmod 600 /swapfile
mkswap /swapfile
swapon /swapfile
swapon --show
cp /etc/fstab /etc/fstab.bak
echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab

systemctl enable firewalld
firewall-cmd --permanent --add-port=1-65535/tcp
firewall-cmd --reload
systemctl start firewalld

echo "Include /etc/ssh/sshd_config.d/*.conf" > /etc/ssh/sshd_config
echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config
echo "ChallengeResponseAuthentication no" >> /etc/ssh/sshd_config
echo "UsePAM yes" >> /etc/ssh/sshd_config
echo "X11Forwarding yes" >> /etc/ssh/sshd_config
echo "PrintMotd no" >> /etc/ssh/sshd_config
echo "AcceptEnv LANG LC_*" >> /etc/ssh/sshd_config
echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
echo "Subsystem       sftp    /usr/lib/openssh/sftp-server" >> /etc/ssh/sshd_config
service ssh restart

apt install openvpn easy-rsa -y
apt install openvpn -y

cd /etc/openvpn/

echo "dev tun" > /etc/openvpn/cliente.conf
echo "proto udp" >> /etc/openvpn/cliente.conf
echo "remote 0.0.0.0" >> /etc/openvpn/cliente.conf
echo "port 1194" >> /etc/openvpn/cliente.conf
echo "compress lz4" >> /etc/openvpn/cliente.conf
echo "ifconfig 10.1.0.2 10.1.0.1" >> /etc/openvpn/cliente.conf
echo "route 192.168.1.140 255.255.255.0 10.1.0.1" >> /etc/openvpn/cliente.conf
echo "secret matriz.key" >> /etc/openvpn/cliente.conf
echo "persist-tun" >> /etc/openvpn/cliente.conf
echo "persist-key" >> /etc/openvpn/cliente.conf
echo "ping 15" >> /etc/openvpn/cliente.conf
echo "ping-restart 45" >> /etc/openvpn/cliente.conf
echo "verb 4" >> /etc/openvpn/cliente.conf

echo "#" > /etc/openvpn/matriz.key
echo "# 2048 bit OpenVPN static key" >> /etc/openvpn/matriz.key
echo "#" >> /etc/openvpn/matriz.key
echo "-----BEGIN OpenVPN Static key V1-----" >> /etc/openvpn/matriz.key
echo "3dc37f35e270a8fa78659561dadf9518" >> /etc/openvpn/matriz.key
echo "7025eac25456baadbed969308167bb4c" >> /etc/openvpn/matriz.key
echo "1e4782edbcbc3838ec8063a369b58461" >> /etc/openvpn/matriz.key
echo "8cdba30d408d290d5b68bbf716b7a2a7" >> /etc/openvpn/matriz.key
echo "062ef7ad86678f0b4d7c037bd85265bb" >> /etc/openvpn/matriz.key
echo "1045cf7c3d07a78471889212cdf8ad8f" >> /etc/openvpn/matriz.key
echo "4176b667a7176208f7a97397fac1587b" >> /etc/openvpn/matriz.key
echo "beaae59b45030e631ddb1349670eb3b6" >> /etc/openvpn/matriz.key
echo "15efea2c1825dfdea7817f89732c32bc" >> /etc/openvpn/matriz.key
echo "3780925bc10ffcd4c1a9addc1cffc02d" >> /etc/openvpn/matriz.key
echo "4bde6291290e1ec1f2bca8db0cffcacc" >> /etc/openvpn/matriz.key
echo "a7fae80dde469f1e5a6a92c49fa54a28" >> /etc/openvpn/matriz.key
echo "ae8f130cb7ef503aa8840080deef8bea" >> /etc/openvpn/matriz.key
echo "1ecc2e10199f0c2281f84bd7f75fb017" >> /etc/openvpn/matriz.key
echo "0417752654ac2051fc22f9468d44e70c" >> /etc/openvpn/matriz.key
echo "33ffb6cc58ac11f80ce86dc1fb3fa2da" >> /etc/openvpn/matriz.key
echo "-----END OpenVPN Static key V1-----" >> /etc/openvpn/matriz.key

openvpn --config cliente.conf

systemctl enable openvpn@cliente.service
