#!/bin/bash

sudo -i

timedatectl set-timezone America/Sao_Paulo

apt update -y && apt upgrade -y && apt autoremove -y 

apt-get install \
jq \
wget \
curl \
udisks2 \
libglib2.0-bin \
network-manager \
iputils-ping \
firewalld \
vim \
openssh-server \
dbus -y

fallocate -l 3G /swapfile
chmod 600 /swapfile
mkswap /swapfile
swapon /swapfile
swapon --show
cp /etc/fstab /etc/fstab.bak
echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab

systemctl enable firewalld
firewall-cmd --permanent --add-port=1-65535/tcp
firewall-cmd --reload
systemctl start firewalld

echo "Include /etc/ssh/sshd_config.d/*.conf" > /etc/ssh/sshd_config
echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config
echo "ChallengeResponseAuthentication no" >> /etc/ssh/sshd_config
echo "UsePAM yes" >> /etc/ssh/sshd_config
echo "X11Forwarding yes" >> /etc/ssh/sshd_config
echo "PrintMotd no" >> /etc/ssh/sshd_config
echo "AcceptEnv LANG LC_*" >> /etc/ssh/sshd_config
echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
echo "Subsystem       sftp    /usr/lib/openssh/sftp-server" >> /etc/ssh/sshd_config
service ssh restart

apt install openvpn easy-rsa
apt install openvpn

cd /etc/openvpn/

echo "dev tun" > /etc/openvpn/servidor.conf
echo "proto udp" >> /etc/openvpn/servidor.conf
echo "porta 1194" >> /etc/openvpn/servidor.conf
echo "compress lz4" >> /etc/openvpn/servidor.conf
echo "ifconfig 10.1.0.1 10.1.0.2" >> /etc/openvpn/servidor.conf
echo "route 192.168.1.1 255.255.255.0 10.1.0.2" >> /etc/openvpn/servidor.conf
echo "secret matriz.kez" >> /etc/openvpn/servidor.conf
echo "persist-tun" >> /etc/openvpn/servidor.conf
echo "persist-key" >> /etc/openvpn/servidor.conf
echo "ping 15" >> /etc/openvpn/servidor.conf
echo "ping-restart 45" >> /etc/openvpn/servidor.conf
echo "verb 4" >> /etc/openvpn/servidor.conf

systemctl enable openvpn@servidor.service

openvpn --genkey --secret matriz.key

cat matriz.key
