#!/bin/bash

sudo -i

timedatectl set-timezone America/Sao_Paulo

apt update -y && apt upgrade -y && apt autoremove -y 

systemctl stop zigbee2mqtt

cd /opt/zigbee2mqtt

cp -R data data-backup

git pull

npm ci

cp -R data-backup/* data

rm -rf data-backup

systemctl start zigbee2mqtt
